export const posts = [
  {
    id: 0,
    image: "https://avatarko.ru/img/kartinka/3/zhivotnye_medved_lampa_2384.jpg",
    text: "Lorem Ipsum is simply dummy text of the printing and  typesetting industry...",
    date: "28.08.2022",
    lesson_num: 0,
    title: "What is Lorem Ipsum?",
    author: 0,
  },
  {
    id: 1,
    image: "https://avatarko.ru/img/kartinka/9/robot_medved_8715.jpg",
    text: "Lorem Ipsum is simply dummy text of the printing and  typesetting industry...",
    date: "28.08.2022",
    lesson_num: 0,
    title: "What is Lorem Ipsum?",
    author: 0,
  },
  {
    id: 2,
    text: "Lorem Ipsum is simply dummy text of the printing and  typesetting industry...",
    date: "28.08.2022",
    lesson_num: 0,
    title: "What is Lorem Ipsum?",
    author: 0,
  },
  {
    id: 3,
    image: "https://avatarko.ru/img/kartinka/2/multfilm_robot_1481.jpg",
    text: "Lorem Ipsum is simply dummy text of the printing and  typesetting industry...",
    date: "28.08.2022",
    lesson_num: 0,
    title: "What is Lorem Ipsum?",
    author: 0,
  },
  {
    id: 4,
    text: "Lorem Ipsum is simply dummy text of the printing and  typesetting industry...",
    date: "28.08.2022",
    lesson_num: 0,
    title: "What is Lorem Ipsum?",
    author: 0,
  },
  {
    id: 5,
    text: "Lorem Ipsum is simply dummy text of the printing and  typesetting industry...",
    date: "28.08.2022",
    lesson_num: 0,
    title: "What is Lorem Ipsum?",
    author: 0,
  },
];
